language: go

go:
  - "1.19"

services:
  - docker

branches:
  only:
    - main

jobs:
  include:
    - stage: CI
      name: "Package & build"    
      before_script:
        - echo "Building Docker"
        - docker-compose up --build
        - sleep 60
    - name: "Unit Tests"
      script:
        - go test -v  ./...

    - stage: Deploy
      if: branch = master
      name: "Dummy deploy stage"
      script:
        - echo "Deploy"